apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: example-recursive-real # defining the real composition
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1beta1
    kind: XR
  mode: Pipeline
  pipeline:
    - step: render-templates
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            apiVersion: s3.aws.upbound.io/v1beta1
            kind: Bucket
            metadata:
              annotations:
                {{ setResourceNameAnnotation "bucket" }}
            spec:
              forProvider:
                region: {{ .observed.composite.resource.spec.region }}
